version: "3.9"

services:
  db:
    image: postgres:17
    env_file: ./env/postgresql.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - desafio-itau-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - desafio-itau-net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.9.2
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - "5000:5000"
    networks:
      - desafio-itau-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.2
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - desafio-itau-net

  app:
    image: jjosejunior/desafio-itau:latest
    env_file: ./env/app.env
    networks:
      - desafio-itau-net
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - desafio-itau-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  desafio-itau-net:
    driver: overlay

volumes:
  pgdata:
