version: '3.8'

services:
  db:
    image: postgres:17
    env_file: ./env/postgresql.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h db"]
      interval: 5s
      timeout: 5s
      retries: 10

  
  app:
    build:
      context: .
    env_file: ./env/app.env
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy


volumes:
  pgdata: