name: Proposta de CI/CD com docker swarm

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: SSH_PRIVATE_KEY

      - name: Copy docker-stack.yml to remote server
        run: |
          scp -o StrictHostKeyChecking=no docker-stack.yml ec2-user@IP_DO_SERVIDOR_EC2:/home/ec2-user/

      - name: SSH into remote server, build image and deploy stack
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@IP_DO_SERVIDOR_EC2 "
            cd /home/ec2-user && \
            docker build -t jjosejunior/desafio-itau:latest . && \
            docker stack deploy -c docker-stack.yml desafio-itau
          "
